"""Deterministic Airflow DAG source from a validated layout + source config.

The generated file is a static body plus one ``CONFIG`` literal produced by ``pprint``; no user value is ever
interpolated into code or SQL text, so a hostile parameter can at worst become a harmless string literal.
"""

from __future__ import annotations

import pprint
from typing import Any

HEAD = '''"""Generated by lake_fabric for DAG '{dag_id}' ({source_type} -> bronze -> silver -> gold on Trino/Iceberg).

Regenerate from the spec instead of editing by hand.
"""

from __future__ import annotations

{csv_import}import hashlib
import json
import logging
from datetime import datetime, timezone
{stdlib_extra}{third_party}
try:  # Airflow 3
    from airflow.sdk import {sdk_names}
except ImportError:  # Airflow 2
    from airflow.decorators import dag, task
    from airflow.operators.python import get_current_context
{airflow2_extra}from airflow.exceptions import AirflowFailException
from airflow.providers.trino.hooks.trino import TrinoHook

log = logging.getLogger(__name__)

CONFIG = {config}

CHUNK_ROWS = 200
'''

COMMON = '''

def _normalise(value, kind):
    """Landing format for bronze (VARCHAR): ISO date/timestamp in UTC, lower-case booleans, JSON for nested values."""
    if value is None or (isinstance(value, str) and value.strip() == ""):
        return None
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False)
    if kind in ("date", "timestamp"):
        text = value.isoformat() if hasattr(value, "isoformat") else str(value).strip()
        try:
            moment = datetime.fromisoformat(text.replace("Z", "+00:00"))
        except ValueError:
            return str(value)
        if moment.tzinfo is not None:
            moment = moment.astimezone(timezone.utc).replace(tzinfo=None)
        return moment.strftime("%Y-%m-%d") if kind == "date" else moment.strftime("%Y-%m-%d %H:%M:%S.%f")
    if kind == "boolean":
        return str(value).strip().lower()
    return str(value)


def _select(data, records_path):
    for key in filter(None, (records_path or "").split(".")):
        data = data[key]
    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list):
        raise AirflowFailException(f"records_path {records_path!r} does not point to a list of records")
    return data


def _dig(data, path):
    for key in path.split("."):
        if not isinstance(data, dict):
            return None
        data = data.get(key)
    return data


def _comparable(value, kind):
    """Value in a form that can be compared with the watermark (numbers as numbers, dates as ISO strings)."""
    if value is None:
        return None
    if kind in ("bigint", "double"):
        try:
            return float(value)
        except (TypeError, ValueError):
            return None
    return _normalise(value, kind)


def _watermark():
    """Highest watermark already in silver (None on the first run or when the load is not incremental)."""
    mark = CONFIG["watermark"]
    if not mark:
        return None
    value = _scalar(mark["sql"])
    return None if value is None else _normalise(value, mark["type"])


def _only_new(records, watermark):
    """Keep records at or after the watermark (>= so rows sharing the boundary value are never lost; merge de-duplicates)."""
    mark = CONFIG["watermark"]
    if not mark or watermark is None:
        return records
    limit = _comparable(watermark, mark["type"])
    kept = [r for r in records if (v := _comparable(r.get(mark["source_name"]), mark["type"])) is not None and v >= limit]
    log.info("incremental: %s of %s records at or after %s", len(kept), len(records), watermark)
    return kept


def _run(sql, parameters=None):
    return TrinoHook(trino_conn_id=CONFIG["trino_conn_id"]).run(sql, parameters=parameters)


def _scalar(sql, parameters=None):
    return TrinoHook(trino_conn_id=CONFIG["trino_conn_id"]).get_records(sql, parameters=parameters)[0][0]
'''

READERS = {
    "csv": '''

def _read_records(watermark=None):
    src = CONFIG["source"]
    with open(src["path"], newline="", encoding=src["encoding"]) as fh:
        return list(csv.DictReader(fh, delimiter=src["delimiter"]))
''',
    "json": '''

def _read_records(watermark=None):
    src = CONFIG["source"]
    with open(src["path"], encoding=src["encoding"]) as fh:
        if src["path"].endswith(".jsonl"):
            data = [json.loads(line) for line in fh if line.strip()]
        else:
            data = json.load(fh)
    return _select(data, src["records_path"])
''',
    "xlsx": '''

def _read_records(watermark=None):
    src = CONFIG["source"]
    workbook = load_workbook(src["path"], read_only=True, data_only=True)
    sheet = workbook[src["sheet"]] if src["sheet"] else workbook.active
    rows = sheet.iter_rows(values_only=True)
    header = [str(h).strip() if h is not None else "" for h in next(rows)]
    return [dict(zip(header, row)) for row in rows if any(v is not None for v in row)]
''',
    "api": '''

def _headers():
    src = CONFIG["source"]
    headers = {"Accept": "application/json"}
    if src["auth_conn_id"]:
        headers["Authorization"] = f"Bearer {BaseHook.get_connection(src['auth_conn_id']).password}"
    return headers


def _read_records(watermark=None):
    src, pager, mark = CONFIG["source"], CONFIG["source"]["pagination"], CONFIG["watermark"]
    query, url, cursor, records = dict(src["query"]), src["url"], None, []
    if watermark is not None and mark and mark["param"]:
        query[mark["param"]] = watermark
    for page_no in range(1, (pager["max_pages"] if pager else 1) + 1):
        params = dict(query)
        if pager and pager["mode"] == "cursor" and cursor is not None:
            params[pager["cursor_param"]] = cursor
        if pager and pager["mode"] == "page":
            params[pager["page_param"]] = page_no
            if pager["page_size_param"]:
                params[pager["page_size_param"]] = pager["page_size"]
        response = requests.request(src["method"], url, params=params or None, headers=_headers(), timeout=src["timeout"])
        response.raise_for_status()
        body = response.json()
        batch = _select(body, src["records_path"])
        records.extend(batch)
        if not pager:
            break
        if pager["mode"] == "page":
            if not batch:
                break
            continue
        following = _dig(body, pager["next_path"])
        if not following:
            break
        if pager["mode"] == "cursor":
            cursor = following
        else:  # next_link: the link already carries its query; never follow it to another host with our credentials
            if urlparse(following).netloc != urlparse(src["url"]).netloc:
                raise AirflowFailException(f"next link points to another host: {following!r}")
            url, query = following, {}
    else:
        raise AirflowFailException(f"pagination did not finish within {pager['max_pages'] if pager else 1} pages")
    return records
''',
    "mcp": '''

def _headers():
    src = CONFIG["source"]
    headers = {"Accept": "application/json"}
    if src["auth_conn_id"]:
        headers["Authorization"] = f"Bearer {BaseHook.get_connection(src['auth_conn_id']).password}"
    return headers


def _read_records(watermark=None):
    """Call one tool of an MCP server over HTTP (JSON-RPC ``tools/call``) and take its JSON payload as records."""
    src = CONFIG["source"]
    payload = {"jsonrpc": "2.0", "id": 1, "method": "tools/call",
               "params": {"name": src["tool"], "arguments": src["arguments"]}}
    response = requests.post(src["url"], json=payload, headers=_headers(), timeout=src["timeout"])
    response.raise_for_status()
    body = response.json()
    if "error" in body:
        raise AirflowFailException(f"MCP error: {body['error']}")
    result = body["result"]
    if result.get("isError"):
        raise AirflowFailException(f"MCP tool {src['tool']!r} reported an error")
    content = result.get("structuredContent")
    if content is None:
        content = json.loads(next(c["text"] for c in result["content"] if c.get("type") == "text"))
    return _select(content, src["records_path"])
''',
}

DAG = '''

@dag(
    dag_id=CONFIG["dag_id"],
    schedule=CONFIG["schedule"],
    start_date=datetime.fromisoformat(CONFIG["start_date"]).replace(tzinfo=timezone.utc),
    catchup=CONFIG["catchup"],
    default_args={"retries": CONFIG["retries"]},
    max_active_runs=1,
    tags=CONFIG["tags"],
)
def medallion_ingest():
    @task
    def ensure_tables() -> bool:
        for statement in CONFIG["sql"]["ddl"]:
            _run(statement)
        return True

    @task
    def load_bronze(ready: bool) -> str:
        # The batch id is derived from the DAG run, so a retry of the same run replaces its own rows instead of duplicating them.
        run_id = get_current_context()["run_id"]
        batch_id = hashlib.sha1(f"{CONFIG['dag_id']}:{run_id}".encode()).hexdigest()[:32]
        _run(CONFIG["sql"]["bronze_reset"], [batch_id])
        ingested_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S.%f")
        columns = CONFIG["columns"]
        watermark = _watermark()
        records = _only_new(_read_records(watermark), watermark)
        rows = [[_normalise(rec.get(c["source_name"]), c["type"]) for c in columns] + [batch_id, CONFIG["source_label"], ingested_at]
                for rec in records]
        marks = "(" + ", ".join(["?"] * (len(columns) + 3)) + ")"
        for start in range(0, len(rows), CHUNK_ROWS):
            chunk = rows[start:start + CHUNK_ROWS]
            _run(CONFIG["sql"]["bronze_insert"] + ", ".join([marks] * len(chunk)), [v for row in chunk for v in row])
        log.info("bronze: %s rows landed in batch %s", len(rows), batch_id)
        return batch_id

    @task
    def quality_gate(batch_id: str) -> str:
        if _scalar(CONFIG["sql"]["bronze_count"], [batch_id]) == 0:
            if CONFIG["watermark"]:
                log.info("no new rows since the last watermark")
                return batch_id
            raise AirflowFailException("the source produced no rows")
        for key, sql in CONFIG["sql"]["bronze_null_keys"].items():
            nulls = _scalar(sql, [batch_id])
            if nulls:
                raise AirflowFailException(f"{nulls} row(s) with a null business key {key!r}")
        return batch_id

    @task
    def bronze_to_silver(batch_id: str) -> str:
        for statement in CONFIG["sql"]["silver_load"]:
            _run(statement, [batch_id] if "?" in statement else None)
        return batch_id

    @task
    def refresh_gold(batch_id: str) -> None:
        _run(CONFIG["sql"]["gold_refresh"])

    refresh_gold(bronze_to_silver(quality_gate(load_bronze(ensure_tables()))))


medallion_ingest()
'''

THIRD_PARTY = {"xlsx": "\nfrom openpyxl import load_workbook\n", "api": "\nimport requests\n", "mcp": "\nimport requests\n"}
STDLIB_EXTRA = {"api": "from urllib.parse import urlparse\n"}
TASKS = ("ensure_tables", "load_bronze", "quality_gate", "bronze_to_silver", "refresh_gold")


def render_dag(config: dict[str, Any]) -> str:
    kind = config["source"]["type"]
    needs_hook = kind in ("api", "mcp")
    text = HEAD.format(
        dag_id=config["dag_id"], source_type=kind, csv_import="import csv\n" if kind == "csv" else "", stdlib_extra=STDLIB_EXTRA.get(kind, ""), third_party=THIRD_PARTY.get(kind, ""),
        sdk_names="BaseHook, dag, get_current_context, task" if needs_hook else "dag, get_current_context, task",
        airflow2_extra="    from airflow.hooks.base import BaseHook\n" if needs_hook else "",
        config=pprint.pformat(config, width=110, sort_dicts=False))
    return "\n".join(line.rstrip() for line in (text + COMMON + READERS[kind] + DAG).splitlines()) + "\n"
